### ISSUE TITLE
If I set navigationBarBackButtonHidden() and use extension to enable swipe back gesture would cause navigation problem

### ISSUE THREAD

**Issue by nick-maker** [obvios/Routing#3]
Hi @obvios, thank you for this library. I followed your blog, however, I encountered some issues.

After setting my `navigationBarBackButtonHidden()`,  and using the extension from [StackOverflow](https://stackoverflow.com/questions/59921239/hide-navigation-bar-without-losing-swipe-back-gesture-in-swiftui/60067869#60067869), when swiping back, the navigationStack is not removing the view.
```swift
extension UINavigationController: UIGestureRecognizerDelegate {

  // MARK: Open

  open override func viewDidLoad() {
    super.viewDidLoad()
    interactivePopGestureRecognizer?.delegate = self
  }

  // MARK: Public

  public func gestureRecognizerShouldBegin(_ gestureRecognizer: UIGestureRecognizer) -> Bool {
    viewControllers.count > 1
  }
}
```
Please let me know what could be the solution to this issue, thank you very much.

**Comment by obvios** [comment]
Hi

Thank you for reading! Would you be able to share a sample of your code? Specifically I want to know if and how you are using UIkit + SwiftUI together.

I also want to see how you are using the Routing code within your SwiftUI view code.

Thank you.

**Comment by nick-maker** [comment]
Hi 

Thank you for getting back to me. I was trying to share a sample of code while simplifying my code, I realized the problem.
It turns out that it's due to another `NavigationStack` in my `HomeView`, after removing it, the code works normally.

`HomeView`
```swift
var body {
  .overlay {
   NavigationStack {  // should remove this.
        LoginView(model: model)
      .opacity(isLogin ? 0 : 1)
    }
}
```

**Comment by obvios** [comment]
Ah yes, SwiftUI won't allow you to nest `NavigationStack`. Glad you found the issue, I will close this issue now.
