### ISSUE TITLE
Navigation via sheets or fullscreencovers not working. 

### ISSUE THREAD

**Issue by rnic99** [obvios/Routing#4]
Hello! 

I am trying to use this library but I am running into an issue with navigation on sheets and fullscreen covers. The app I am building occasionally requires nested navigation on these types of views but I havent been able to successfully push a new page on top of either the sheet/fullscreen, is this expected behavior? If it is expected behavior how would you recommend I go about making this type of navigation possible? 

**Example pseudo code below:**
- Starting on a basic test view I call router.routeTo(.test1), case test1 is a .sheet navigation type 

- Upon navigating to the test1 view I want to continue navigation to a new page test2 nested in the sheet. 

- So on the test1 view I have a button with an action with router.routeTo(.test2). This however does not work ive tried setting it as all the three navigation types .push/.sheet/.fullscreen but no options are working.

Any assistance would be greatly appreciated. Thanks!

**Comment by rnic99** [comment]
Update: I tested this by putting a stock navigation stack inside of the test1 view and instead of using the router.routeTo  I created a
 NavigationLink("Test2"){
        TestView2()
 }

This worked allowing me to navigate to the TestView2 page on the sheet still.

**Comment by obvios** [comment]
Hi @rnic99 ,

The router object will not work within the context of a sheet or full screen cover as implemented today. This was not in the original design of the library but I am working to add that capability soon.

Thank you for sharing your workaround, this gives me an idea of how the library could be updated to support stack navigation within a sheet/full screen cover.

**Comment by obvios** [comment]
Hi @rnic99 ,

I just wanted to inform you that starting with [v2.0.0](https://github.com/obvios/Routing/releases/tag/v2.0.0) you no longer need to manually add a `NavigationStack` to your presented views, the routing library will take care of that automatically!

Check it out by upgrading to **v2.0.0**
